### ISSUE TITLE
Error: Couldn't find preset "latest"

### ISSUE THREAD

**Issue by holic-cl** [sergeyloysha/vue-spinner-component#1]
Hi, i was trying to use the spinner, but something fails to me:
```
Module build failed: Error: Couldn't find preset "latest" relative to directory "/home/holic/dev/ryft-labs/ryft-admin/node_modules/vue-spinner-component"
```

Do you have any clue? i am doing something wrong?
regards

**Comment by rajeshkos** [comment]
Getting same error. Any solution ?

**Comment by Aukemid** [comment]
I got the same error. Adding "babel-preset-latest": "^6.24.1" to package.json solved it for me.
