### ISSUE TITLE
rotateClockwise invalid character

### ISSUE THREAD

**Issue by Aukemid** [sergeyloysha/vue-spinner-component#2]
The C in rotateClockwise and rotateCounterClockwise is not the character "C". See [Spinner.vue](https://github.com/sergeyloysha/vue-spinner-component/blob/master/src/Spinner.vue) and use the browser to search for "c".

In my build Chrome shows rotateÐ¡lockwise.

Copied from the source: rotateСlockwise
Typed manually: rotateClockwise
(Search "c")

Edit:
I've fixed it in [a fork](https://github.com/Aukemid/vue-spinner-component) and made a [Pull request](https://github.com/sergeyloysha/vue-spinner-component/pull/3).

**Comment by da-sloysha** [comment]
Merged. Thanks.
